[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
blueshift_anchor_flash_loan = "9ewZK3M7tG8kgcWhHiy33iTbcYpzkiof8L8XZzhSb6np"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
